force-app/main/default/objects/RecordTypeMappingCmdt__mdt/RecordTypeMappingCmdt__mdt.object-meta.xml
<CustomObject>
	<label>RecordTypeMappingCmdt</label>
	<pluralLabel>RecordTypeMappingCmdt</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordTypeMappingCmdt__mdt/fields/CountryCode__c.field-meta.xml
<CustomField>
	<fullName>CountryCode__c</fullName>
	<description>The name of a CountryCode picklist value.</description>
	<inlineHelpText>The name of a CountryCode picklist value.</inlineHelpText>
	<label>CountryCode</label>
	<type>Text</type>
	<length>10</length>
</CustomField>

force-app/main/default/objects/RecordTypeMappingCmdt__mdt/fields/Industry__c.field-meta.xml
<CustomField>
	<fullName>Industry__c</fullName>
	<description>The name of a picklist value in the Lead Industry picklist.</description>
	<inlineHelpText>The name of a picklist value in the Lead Industry picklist.</inlineHelpText>
	<label>Industry</label>
	<type>Text</type>
	<length>255</length>
</CustomField>

force-app/main/default/objects/RecordTypeMappingCmdt__mdt/fields/RecordTypeName__c.field-meta.xml
<CustomField>
	<fullName>RecordTypeName__c</fullName>
	<description>The name of the record type to apply to the Lead when the Industry and Country values match this custom setting's Industry and Country values.</description>
	<inlineHelpText>The name of the record type to apply to the Lead when the Industry and Country values match this custom setting's Industry and Country values.</inlineHelpText>
	<label>Record Type Name</label>
	<type>Text</type>
	<length>255</length>
</CustomField>

force-app/main/default/classes/CustomSettingsService.cls
public with sharing class CustomSettingsService {
    
    //Return a record that shows whether the RecordTypeMapping feature is enabled
    public FeatureSettings__c getMapperEnablementRecord() {
        return FeatureSettings__c.getInstance();
    }

    //Update the org-level custom setting
    //Returns the original value
    public Boolean updateMapperEnablementRecord(Boolean newValue) {
        FeatureSettings__c enablementRecord = [Select Id, FeatureEnabled__c from FeatureSettings__c LIMIT 1];
        Boolean originalValue = enablementRecord.FeatureEnabled__c;

        enablementRecord.FeatureEnabled__c = newValue;
        update enablementRecord;

        return originalValue;
    }

    //Return a record that shows which record type name to use for the given countryCode
    //and industry values on a new lead.
    public RecordTypeMappingCmdt__mdt getRecordTypeMapping(String countryCode, String industry) {
        RecordTypeMappingCmdt__mdt mapping = null;

        List<RecordTypeMappingCmdt__mdt> mappings =  [SELECT Id, RecordTypeName__c FROM RecordTypeMappingCmdt__mdt 
                WHERE CountryCode__c = :countryCode AND Industry__c = :industry];
        if (mappings.size() > 0) {
            mapping = mappings.get(0);
        }
        return mapping;
    }

    
}